// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/cache-service.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SetRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRequest) Reset()         { *m = SetRequest{} }
func (m *SetRequest) String() string { return proto.CompactTextString(m) }
func (*SetRequest) ProtoMessage()    {}
func (*SetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a309f1d37d50b77d, []int{0}
}

func (m *SetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRequest.Unmarshal(m, b)
}
func (m *SetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRequest.Marshal(b, m, deterministic)
}
func (m *SetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRequest.Merge(m, src)
}
func (m *SetRequest) XXX_Size() int {
	return xxx_messageInfo_SetRequest.Size(m)
}
func (m *SetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetRequest proto.InternalMessageInfo

func (m *SetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SetRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type GetRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a309f1d37d50b77d, []int{1}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type SetUserRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Class                string   `protobuf:"bytes,2,opt,name=class,proto3" json:"class,omitempty"`
	RollNum              int64    `protobuf:"varint,3,opt,name=roll_num,json=rollNum,proto3" json:"roll_num,omitempty"`
	Metadata             []byte   `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetUserRequest) Reset()         { *m = SetUserRequest{} }
func (m *SetUserRequest) String() string { return proto.CompactTextString(m) }
func (*SetUserRequest) ProtoMessage()    {}
func (*SetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a309f1d37d50b77d, []int{2}
}

func (m *SetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetUserRequest.Unmarshal(m, b)
}
func (m *SetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetUserRequest.Marshal(b, m, deterministic)
}
func (m *SetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUserRequest.Merge(m, src)
}
func (m *SetUserRequest) XXX_Size() int {
	return xxx_messageInfo_SetUserRequest.Size(m)
}
func (m *SetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetUserRequest proto.InternalMessageInfo

func (m *SetUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SetUserRequest) GetClass() string {
	if m != nil {
		return m.Class
	}
	return ""
}

func (m *SetUserRequest) GetRollNum() int64 {
	if m != nil {
		return m.RollNum
	}
	return 0
}

func (m *SetUserRequest) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type GetUserRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RollNum              int64    `protobuf:"varint,2,opt,name=roll_num,json=rollNum,proto3" json:"roll_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a309f1d37d50b77d, []int{3}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetUserRequest) GetRollNum() int64 {
	if m != nil {
		return m.RollNum
	}
	return 0
}

type UserResponse struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Class                string   `protobuf:"bytes,3,opt,name=class,proto3" json:"class,omitempty"`
	RollNum              int64    `protobuf:"varint,4,opt,name=roll_num,json=rollNum,proto3" json:"roll_num,omitempty"`
	Metadata             []byte   `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Status               string   `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a309f1d37d50b77d, []int{4}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *UserResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserResponse) GetClass() string {
	if m != nil {
		return m.Class
	}
	return ""
}

func (m *UserResponse) GetRollNum() int64 {
	if m != nil {
		return m.RollNum
	}
	return 0
}

func (m *UserResponse) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *UserResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type Response struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a309f1d37d50b77d, []int{5}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Response) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*SetRequest)(nil), "proto.SetRequest")
	proto.RegisterType((*GetRequest)(nil), "proto.GetRequest")
	proto.RegisterType((*SetUserRequest)(nil), "proto.SetUserRequest")
	proto.RegisterType((*GetUserRequest)(nil), "proto.GetUserRequest")
	proto.RegisterType((*UserResponse)(nil), "proto.UserResponse")
	proto.RegisterType((*Response)(nil), "proto.Response")
}

func init() {
	proto.RegisterFile("proto/cache-service.proto", fileDescriptor_a309f1d37d50b77d)
}

var fileDescriptor_a309f1d37d50b77d = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4d, 0x4f, 0x02, 0x31,
	0x10, 0x4d, 0x59, 0x3e, 0x27, 0x04, 0xb5, 0x7e, 0x64, 0xe1, 0x60, 0x48, 0x0f, 0x66, 0x39, 0x08,
	0x89, 0x48, 0xe2, 0xcd, 0xc4, 0x0b, 0x27, 0x3d, 0x6c, 0xe3, 0xc5, 0x8b, 0x29, 0x65, 0x22, 0xc4,
	0x5d, 0x16, 0xb6, 0x2d, 0x09, 0x3f, 0xc5, 0x7f, 0xe5, 0x4f, 0x32, 0x74, 0x17, 0xd8, 0x35, 0x7c,
	0x9c, 0xda, 0x37, 0x79, 0xef, 0xb5, 0x33, 0x6f, 0xa0, 0x39, 0x8f, 0x23, 0x1d, 0xf5, 0xa4, 0x90,
	0x13, 0xbc, 0x57, 0x18, 0x2f, 0xa7, 0x12, 0xbb, 0xb6, 0x46, 0x4b, 0xf6, 0x60, 0x8f, 0x00, 0x1c,
	0xb5, 0x8f, 0x0b, 0x83, 0x4a, 0xd3, 0x73, 0x70, 0xbe, 0x71, 0xe5, 0x92, 0x36, 0xf1, 0x6a, 0xfe,
	0xfa, 0x4a, 0xaf, 0xa0, 0xb4, 0x14, 0x81, 0x41, 0xb7, 0xd0, 0x26, 0x5e, 0xdd, 0x4f, 0x00, 0xbb,
	0x05, 0x18, 0x1e, 0x51, 0xb1, 0x05, 0x34, 0x38, 0xea, 0x77, 0x85, 0xf1, 0x86, 0x43, 0xa1, 0x38,
	0x13, 0x21, 0xa6, 0x24, 0x7b, 0x5f, 0x7b, 0xcb, 0x40, 0x28, 0x65, 0xbd, 0x6b, 0x7e, 0x02, 0x68,
	0x13, 0xaa, 0x71, 0x14, 0x04, 0x9f, 0x33, 0x13, 0xba, 0x4e, 0x9b, 0x78, 0x8e, 0x5f, 0x59, 0xe3,
	0x37, 0x13, 0xd2, 0x16, 0x54, 0x43, 0xd4, 0x62, 0x2c, 0xb4, 0x70, 0x8b, 0xf6, 0x3f, 0x5b, 0xcc,
	0x9e, 0xa1, 0x31, 0x3c, 0xfd, 0x64, 0xd6, 0xbc, 0x90, 0x33, 0x67, 0x3f, 0x04, 0xea, 0x89, 0x5c,
	0xcd, 0xa3, 0x99, 0xc2, 0x3d, 0xc3, 0xd8, 0x38, 0x16, 0xf6, 0x35, 0xe1, 0x1c, 0x6a, 0xa2, 0x78,
	0xb8, 0x89, 0x52, 0xbe, 0x09, 0x7a, 0x03, 0x65, 0xa5, 0x85, 0x36, 0xca, 0x2d, 0x5b, 0xb7, 0x14,
	0xb1, 0x27, 0xa8, 0x6e, 0xbf, 0xb5, 0xe3, 0x90, 0x2c, 0x67, 0x7f, 0x52, 0x0f, 0xbf, 0x04, 0x20,
	0x9e, 0x4b, 0x9e, 0x64, 0x4f, 0x3b, 0xe0, 0x0c, 0x51, 0xd3, 0x8b, 0x64, 0x09, 0xba, 0xbb, 0x10,
	0x5b, 0x67, 0x69, 0x69, 0xfb, 0x4e, 0x07, 0x1c, 0x9e, 0xa1, 0xf2, 0x23, 0xd4, 0x01, 0x54, 0xd2,
	0xd9, 0xd3, 0xeb, 0x9d, 0x73, 0x26, 0x8b, 0xd6, 0x65, 0x5a, 0xce, 0x0d, 0x78, 0x00, 0x15, 0xfe,
	0x4f, 0xc6, 0x4f, 0xcb, 0x5e, 0xbc, 0x8f, 0xbb, 0xaf, 0xa9, 0x9e, 0x98, 0x51, 0x57, 0x46, 0x61,
	0x8f, 0xaf, 0x70, 0xfc, 0x2a, 0xfa, 0xf9, 0x1d, 0xef, 0x59, 0xd9, 0xa8, 0x6c, 0x8f, 0xfe, 0x5f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xb5, 0x37, 0x00, 0x85, 0x07, 0x03, 0x00, 0x00,
}
